// Script to generate en_US.ts based on zh_CN.ts
import { readFileSync, writeFileSync } from 'fs';

const zhContent = readFileSync('e:/lixycode/dynamicform/src/lang/zh_CN.ts', 'utf-8');

// Extract all key-value pairs from zh_CN.ts
const kvPairs = [];
const lines = zhContent.split('\n');
let i = 0;
while (i < lines.length) {
  const line = lines[i].trim();
  // Skip comments, empty lines, export default, braces
  if (!line || line.startsWith('//') || line.startsWith('/*') || line.startsWith('*') || line === 'export default {' || line === '};' || line === '{') {
    i++;
    continue;
  }
  // Match "key": value format
  const kvMatch = line.match(/^"([^"]+)":\s*(.+),?$/);
  if (kvMatch) {
    const key = kvMatch[1];
    let value = kvMatch[2].replace(/,\s*$/, '').trim();
    // Handle template strings (backticks)
    if (value.startsWith('`')) {
      let fullValue = value;
      while (!fullValue.endsWith('`') || fullValue === '`') {
        i++;
        fullValue += '\n' + lines[i];
      }
      kvPairs.push({ key, value: fullValue, isTemplate: true });
    } else if (value.startsWith('"') && value.endsWith('"')) {
      kvPairs.push({ key, value: value.slice(1, -1), isTemplate: false });
    } else if (value.startsWith('Config.')) {
      kvPairs.push({ key, value, isSpecial: true });
    } else {
      kvPairs.push({ key, value, isTemplate: false });
    }
  }
  i++;
}

console.log(`Total keys extracted: ${kvPairs.length}`);

// Translation map - comprehensive Chinese to English mapping
const translations = {
  // starhorse
  "添加模块": "Add Module",
  "欢迎使用系统": "Welcome to the System",
  "您还没有配置任何模块，请添加您的第一个模块": "You haven't configured any modules yet, please add your first module",
  "选择模块": "Select Module",
  "搜索模块...": "Search Modules...",
  "添加选中模块": "Add Selected Modules",
  "全部": "All",
  "系统管理": "System Management",
  "业务模块": "Business Modules",
  "数据分析": "Data Analysis",
  "工具": "Tools",
  "用户管理": "User Management",
  "管理系统用户和权限": "Manage system users and permissions",
  "系统监控": "System Monitoring",
  "查看系统运行状态": "View system running status",
  "个人中心": "Personal Center",
  "查看和编辑个人信息": "View and edit personal information",
  "请输入": "Please input",
  "请选择": "Please select",
  "不能为空": "Cannot be empty",
  "密码登录": "Password Login",
  "扫码登录": "Scan Code Login",
  "其它登录方式": "Other Login Methods",
  "微信": "WeChat",
  "支付宝": "Alipay",
  "微博": "Weibo",
  "验证码": "Verification Code",
  "前后缀配置": "Prefix/Suffix Configuration",
  "前缀文本": "Prefix Text",
  "输入框前面显示的固定文本": "Fixed text displayed in front of the input box",
  "前缀下拉列表": "Prefix Dropdown List",
  "配置输入框前面的下拉选项": "Configure dropdown options in front of the input box",
  "前缀下拉列表配置": "Prefix Dropdown List Configuration",
  "后缀文本": "Suffix Text",
  "输入框后面显示的固定文本": "Fixed text displayed after the input box",
  "后缀操作按钮": "Suffix Action Button",
  "配置输入框后面的操作按钮": "Configure action button after the input box",
  "后缀操作按钮配置": "Suffix Action Button Configuration",
  "后缀下拉列表": "Suffix Dropdown List",
  "配置输入框后面的下拉选项": "Configure dropdown options after the input box",
  "后缀下拉列表配置": "Suffix Dropdown List Configuration",
  "前缀文本和前缀下拉列表不能同时配置": "Prefix text and prefix dropdown list cannot be configured at the same time",
  "后缀文本、后缀操作按钮和后缀下拉列表不能同时配置": "Suffix text, suffix action button and suffix dropdown list cannot be configured at the same time",
  "账  号": "Account",
  "密  码": "Password",
  "记住我": "Remember Me",
  "忘记密码？": "Forgot Password?",
  "没有账号？": "No Account?",
  "记得密码？": "Remember Password?",
  "请输入您注册时使用的邮箱地址，我们将向该邮箱发送密码重置链接。": "Please enter the email address used during registration, we will send a password reset link to that email.",
  "立即注册": "Register Now",
  "登 录": "Login",
  "欢迎光临": "Welcome",
  "取消": "Cancel",
  "欢迎回来": "Welcome Back",
  "登 录 中...": "Logging in...",
  "请检查您的邮箱并按照指示重置密码。": "Please check your email and follow the instructions to reset your password.",
  "用户中心": "User Center",
  "日程表": "Calendar",
  "布局设置": "Layout Settings",
  "修改个人信息": "Edit Profile",
  "退出": "Logout",
  "提交": "Submit",
  "提交并继续": "Submit and Continue",
  "保存": "Save",
  "保存并继续": "Save and Continue",
  "重置": "Reset",
  "最大化": "Maximize",
  "还原": "Restore",
  "关闭": "Close",
  "流程设计": "Flow Design",
  "流程设计器": "Flow Designer",
  "添加节点": "Add Node",
  "开始": "Start",
  "结束": "End",
  "条件分支": "Condition Branch",
  "并行分支": "Parallel Branch",
  "意见分支": "Opinion Branch",
  "用户节点": "User Node",
  "表单节点": "Form Node",
  "审批节点": "Approval Node",
  "会签节点": "Countersign Node",
  "分支节点": "Branch Node",
  "循环节点": "Loop Node",
  "子流程节点": "Sub-process Node",
  "自动节点": "Auto Node",
  "人工节点": "Manual Node",
  "自动审批": "Auto Approve",
  "人工审批": "Manual Approve",
  "自动会签": "Auto Countersign",
  "人工会签": "Manual Countersign",
  "自动分支": "Auto Branch",
  "人工分支": "Manual Branch",
  "自动循环": "Auto Loop",
  "人工循环": "Manual Loop",
  "自动子流程": "Auto Sub-process",
  "人工子流程": "Manual Sub-process",
  "删除节点": "Delete Node",
  "确认删除节点？": "Confirm delete node?",
  "删除节点后，该节点的所有子节点将被删除，确认删除？": "After deleting the node, all child nodes of this node will be deleted. Confirm?",
  "组件": "Component",
  "数据源": "Data Source",
  "图表": "Charts",
  "模板": "Template",
  "帮助": "Help",
  "布局组件": "Layout Components",
  "表单组件": "Form Components",
  "自定义组件": "Custom Components",
  "表单验证通过": "Form validation passed",
  "表单验证失败，请检查输入": "Form validation failed, please check input",
  "表单预览": "Form Preview",
  "HTML文件导出成功": "HTML file exported successfully",
  "校验表单": "Validate Form",
  "导出HTML": "Export HTML",
  "表单属性层级": "Form Property Hierarchy",
  "表单列表": "Form List",
  "欢迎使用表单设计器": "Welcome to Form Designer",
  "请从左侧组件库中选择一个组件，然后用鼠标双击或者拖动该组件放置于此处": "Please select a component from the left component library, then double-click or drag it to place it here",
  "拖拽组件": "Drag Component",
  "配置属性": "Configure Properties",
  "快速构建": "Quick Build",
  "恢复缓存数据": "Restore Cached Data",
  "返回列表": "Back to List",
  "风格": "Style",
  "电脑": "PC",
  "平板": "Tablet",
  "手机": "Mobile",
  "新建": "New",
  "导入": "Import",
  "导出": "Export",
  "修改属性": "Edit Properties",
  "表单层级": "Form Hierarchy",
  "清空元素": "Clear Elements",
  "后退一步": "Undo",
  "前进一步": "Redo",
  "校验": "Validate",
  "预览": "Preview",
  "生成代码": "Generate Code",
  "批量修改属性": "Batch Edit Properties",
  "业务字段": "Business Fields",
  "公共字段": "Common Fields",
  "按钮点击事件": "Button Click Event",
  "加载此模板": "Load This Template",
  "快捷键": "Shortcuts",
  "剪切操作": "Cut",
  "复制操作": "Copy",
  "粘贴操作": "Paste",
  "后退一步操作": "Undo",
  "前进一步操作": "Redo",
  "校验操作": "Validate",
  "新建操作": "New",
  "保存操作": "Save",
  "删除操作": "Delete",
  "全选操作": "Select All",
  "清空操作": "Clear",
  "查找操作": "Find",
  "打开/关闭左侧面板": "Toggle Left Panel",
  "打开/关闭右侧面板": "Toggle Right Panel",
  "更换选中组件": "Change Selected Component",
  "预览操作": "Preview",
  "返回上一个页面": "Go Back to Previous Page",
  "向上移动选中组件": "Move Selected Component Up",
  "向下移动选中组件": "Move Selected Component Down",
  "其它快捷键待更新": "More shortcuts to be updated",
  "描述": "Description",
  "表单设计器是一款通过拖拽即可实现复杂表单模型，可满足大部分常见业务": "The form designer can implement complex form models through drag and drop, meeting most common business needs",
  "规则": "Rules",
  "所有同级组件的名字不能重复，在Tab组件中tabName和objectName不能重复": "All sibling component names cannot be duplicated. In Tab components, tabName and objectName cannot be duplicated",
  "Table组件中batchFieldName不能重复": "In Table components, batchFieldName cannot be duplicated",
  "操作步骤": "Steps",
  "在左边拖动或者双击组件可添加到中间设计舞台": "Drag or double-click a component on the left to add it to the design stage in the middle",
  "在右边属性区域设置选中组件得属性": "Set properties of the selected component in the property area on the right",
  "在头部可批量编辑按钮可编辑属性名称": "Use the batch edit button in the header to edit property names",
  "在头部设置按钮可设置表单属性": "Use the settings button in the header to set form properties",
  "在头部代码按钮可以生成代码（目前只能生成vue3）": "Use the code button in the header to generate code (currently only Vue3)",
  "在头部预览按钮可以预览表单信息": "Use the preview button in the header to preview form information",
  "在舞台上点击鼠标右键可打开右键菜单": "Right-click on the stage to open the context menu",
  "盲点（数据源生成的表单模型）": "Blind Spots (Form Models Generated from Data Sources)",
  "须注意选择器、单选框、多选框等组件的值类型，系统默认是字符串类型，如果数据库设置是数值类型需要在对应字段的属性面板中修改值类型": "Pay attention to the value types of selectors, radio buttons, checkboxes and other components. The system default is string type. If the database setting is numeric type, you need to modify the value type in the corresponding field's property panel",
  "提交时须注意表的主键生成策略，默认是动态赋值，如果是自增，需要在保存时修改主键策略": "When submitting, pay attention to the primary key generation strategy of the table. The default is dynamic assignment. If it is auto-increment, you need to modify the primary key strategy when saving",
  "未实现": "Not Implemented",
  "在配置或者提交功能里设置": "Set in configuration or submit function",
  "表单配置": "Form Configuration",
  "暂存": "Save Draft",
  "代码": "Code",
  "自定义信息": "Custom Information",
  "自定义事件,提供了如下系统参数": "Custom events, the following system parameters are provided",
  "当前组件的信息": "Current component information",
  "表单数据": "Form Data",
  "表单的所有元素": "All form elements",
  "表单实例对象": "Form instance object",
  "具体参数或方法切换Tab查看": "Switch tabs to view specific parameters or methods",
  "当前组件属性": "Current Component Properties",
  "表单实例": "Form Instance",
  "表单属性": "Form Properties",
  "对象名字": "Object Name",
  "名称": "Name",
  "说明": "Description",
  "类型": "Type",
  "对整个表单的内容进行验证。 接收一个回调函数，或返回": "Validate the entire form content. Accepts a callback function or returns",
  "验证具体的某个字段。": "Validate a specific field.",
  "重置该表单项，将其值重置为初始值，并移除校验结果": "Reset the form field, reset its value to the initial value, and remove validation results",
  "滚动到指定的字段": "Scroll to the specified field",
  "清理某个字段的表单验证信息。": "Clear form validation messages for a field.",
  "获取所有字段的 context": "Get context of all fields",
  "参数配置": "Parameter Configuration",
  "请选择主键字段": "Please select a primary key field",
  "请配置回调字段": "Please configure callback fields",
  "根节点": "Root Node",
  "协同插件": "Collaboration Plugin",
  "流程名称": "Process Name",
  "流程分类": "Process Category",
  "是否部署": "Is Deployed",
  "已部署": "Deployed",
  "未部署": "Not Deployed",
  "流程部署ID": "Process Deployment ID",
  "绑定表单信息": "Bind Form Information",
  "图标": "Icon",
  "流程类型": "Process Type",
  "状态": "Status",
  "流程版本": "Process Version",
  "多表单显示模式": "Multi-form Display Mode",
  "流程管理员": "Process Manager",
  "流程Xml文件": "Process XML File",
  "流程Json文件": "Process JSON File",
  "版本号": "Version Number",
  "是否删除": "Is Deleted",
  "数据编号": "Data Number",
  "状态名称": "Status Name",
  "国际编码": "International Code",
  "备注": "Remark",
  "编辑": "Edit",
  "查看": "View",
  "新增": "Add",
  "配置类别": "Configuration Category",
  "编码": "Code",
  "是否选中": "Is Checked",
  "是": "Yes",
  "否": "No",
  "图片地址": "Image URL",
  "节点": "Node",
  "测试报告类型": "Test Report Type",
  "主键": "Primary Key",
  "实例ID": "Instance ID",
  "列索引": "Column Index",
  "执行方式": "Execution Type",
  "程序语言": "Programming Language",
  "项目编码": "Project Code",
  "源码相对目录": "Source Code Relative Directory",
  "执行失败通知": "Execution Failure Notification",
  "执行成功通知": "Execution Success Notification",
  "自定义规则": "Custom Rules",
  "行索引": "Row Index",
  "项目名称": "Project Name",
  "项目类型": "Project Type",
  "实例名称": "Instance Name",
  "是否独占 1是 2否 默认2": "Is Exclusive (1=Yes, 2=No, Default 2)",
  "关联计划": "Linked Plan",
  "Cron定时触发执行": "Cron Scheduled Execution",
  "代码下载后存放目录": "Code Download Directory",
  "是否自动触发构建 1是 2否 默认2": "Auto Trigger Build (1=Yes, 2=No, Default 2)",
  "创建人": "Created By",
  "修改人": "Updated By",
  "创建日期": "Created Date",
  "修改日期": "Updated Date",
  "数据版本号": "Data Version Number",
  "是否已逻辑": "Is Logically Deleted",
  "状态码": "Status Code",
  "状态码名称": "Status Name",
  "国际码": "International Code",
  "代码库类型": "Repository Type",
  "代码库地址": "Repository URL",
  "项目字符集": "Project Charset",
  "流水线账号": "Pipeline Account",
  "流水线密码": "Pipeline Password",
  "项目成员": "Project Members",
  "用户名": "Username",
  "姓名": "Name",
  "工号": "Employee No.",
  "职级": "Rank",
  "岗位": "Position",
  "角色名称": "Role Name",
  "生效时间": "Effective Date",
  "失效日期": "Expiration Date",
  "是否管理员": "Is Manager",
  "所属用户组": "User Group",
  "不能设置空格密码": "Cannot set blank password",
  "请设置长度为6到15的密码": "Please set a password with 6 to 15 characters",
  "两次密码不一致，请重新录入": "Passwords do not match, please re-enter",
  "密码": "Password",
  "确认密码": "Confirm Password",
  "修改密码": "Change Password",
  "区域名称": "Area Name",
  "区域编码": "Area Code",
  "区域主键": "Area Primary Key",
  "父节点编号": "Parent Node Number",
  "请求方法": "Request Method",
  "操作人": "Operator",
  "访问接口": "Access Interface",
  "访问地址": "Access Address",
  "请求参数": "Request Parameters",
  "完成日期": "Completed Date",
  "挂起日期": "Suspended Date",
  "委托日期": "Delegated Date",
  "确认": "Confirm",
  "接口地址": "Interface Address",
  "客户名称": "Customer Name",
  "客户编码": "Customer Code",
  "Logo": "Logo",
  "创建时间": "Created Time",
  "修改时间": "Updated Time",
  "是否逻辑删除": "Is Logically Deleted",
  "部门名称": "Department Name",
  "部门编码": "Department Code",
  "上级部门": "Parent Department",
  "部门领导": "Department Leader",
  "分管领导": "Division Leader",
  "所属公司": "Affiliated Company",
  "部门电话": "Department Phone",
  "部门职责": "Department Responsibility",
  "字典类型名称": "Dictionary Type Name",
  "字典类型编码": "Dictionary Type Code",
  "字典类型": "Dictionary Type",
  "字典名称": "Dictionary Name",
  "字典编码": "Dictionary Code",
  "排序": "Sort",
  "字典描述": "Dictionary Description",
  "字典信息": "Dictionary Information",
  "请先选择字典类别": "Please select a dictionary category first",
  "归属主体": "Belonging Entity",
  "应用名称": "Application Name",
  "添加时间": "Add Time",
  "上级应用": "Parent Application",
  "系统编码": "System Code",
  "系统Logo": "System Logo",
  "数据排序": "Data Sort",
  "系统描述": "System Description",
  "菜单名称": "Menu Name",
  "菜单编码": "Menu Code",
  "菜单图标": "Menu Icon",
  "菜单描述": "Menu Description",
  "原应用": "Original Application",
  "新应用": "New Application",
  "新应用的父级菜单": "Parent Menu of New Application",
  "打开方式": "Open Type",
  "保持活跃": "Keep Alive",
  "菜单切换方式": "Menu Switch Method",
  "移动": "Move",
  "复制": "Copy",
  "菜单列表": "Menu List",
  "原应用菜单": "Original Application Menu",
  "目标应用菜单": "Target Application Menu",
  "退回左边": "Return to Left",
  "添加到右边": "Add to Right",
  "菜单路径": "Menu Path",
  "归属应用名称": "Belonging Application Name",
  "父菜单": "Parent Menu",
  "分类": "Category",
  "类别": "Type",
  "标题": "Title",
  "是否广播消息": "Is Broadcast Message",
  "接收人": "Recipient",
  "跳转Url": "Redirect URL",
  "内容": "Content",
  "系统名称": "System Name",
  "角色Id": "Role ID",
  "系统Id": "System ID",
  "菜单Id": "Menu ID",
  "数据状态码": "Data Status Code",
  "数据状态名称": "Data Status Name",
  "普通用户组": "Normal User Group",
  "高级用户组": "Advanced User Group",
  "超级用户组": "Super User Group",
  "15分钟": "15 Minutes",
  "30分钟": "30 Minutes",
  "60分钟": "60 Minutes",
  "180分钟": "180 Minutes",
  "无限制": "Unlimited",
  "用户组名称": "User Group Name",
  "角色编码": "Role Code",
  "用户组类型": "User Group Type",
  "用户组编码": "User Group Code",
  "会话超时时间": "Session Timeout",
  "系统权限": "System Permissions",
  "菜单权限": "Menu Permissions",
  "用户组职责": "User Group Responsibility",
  "职级名称": "Rank Name",
  "职级编码": "Rank Code",
  "职级排序": "Rank Sort",
  "归属类别": "Belonging Category",
  "审批意见": "Approval Opinion",
  "请选择数据库信息": "Please select database information",
  "请输入关键字": "Please enter keyword",
  "执行": "Execute",
  "停止": "Stop",
  "格式化": "Format",
  "执行Sql前先连接数据库": "Please connect to the database before executing SQL",
  "一次最多只能执行5条Sql": "A maximum of 5 SQL statements can be executed at a time",
  "表名": "Table Name",
  "空标识": "Null Flag",
  "使用说明": "Usage Instructions",
  "目前快捷键失效,提示表字段需先单击表名加载字段到本地": "Currently shortcuts are disabled. To prompt table fields, you need to click the table name first to load fields locally",
  "使用前需先连接数据库;如果在左侧下拉框中,无数据或者无您要连接的DB,请联系管理员配置并授权": "You need to connect to the database before use; if there is no data in the left dropdown or no DB you want to connect to, please contact the administrator to configure and authorize",
  "Sql查询器理论上支持数据库的所有DDL,DML,DCL等操作,但基于合规性,请在配置数据库的时候慎重赋予操作权限": "The SQL executor theoretically supports all DDL, DML, DCL and other operations of the database, but based on compliance, please carefully grant operation permissions when configuring the database",
  "建议不要执行耗时的Sql,容易被网关拦截": "It is recommended not to execute time-consuming SQL, as it may be intercepted by the gateway",
  "建议每条Sql写完后加上,以方便多条sql拆分": "It is recommended to add a semicolon after each SQL statement to facilitate splitting multiple SQL statements",
  "默认每条Sql 一次最多返回10条数据,页面支持最大返回100条配置": "By default, each SQL statement returns up to 10 records, and the page supports a maximum of 100 records configuration",
  "每次最多执行的Sql数不能超过5条,超过数量取前5条": "The maximum number of SQL statements that can be executed each time cannot exceed 5, exceeding this number will take the first 5",
  "执行器支持选中某条Sql进行执行": "The executor supports selecting a specific SQL statement to execute",
  "打开提示": "Open Prompt",
  "未找到相关表": "No related tables found",
  "数据库信息": "Database Information",
  "后端程序语言": "Backend Programming Language",
  "后端模版版本": "Backend Template Version",
  "前端模版版本": "Frontend Template Version",
  "需要生成的表名": "Table Names to Generate",
  "需要排除的表": "Tables to Exclude",
  "去除表前缀": "Remove Table Prefix",
  "包名": "Package Name",
  "要生成的文件": "File Types to Generate",
  "分组条件": "Group Condition",
  "分组列数": "Group Columns",
  "模块相关": "Module Related",
  "模块名称": "Module Name",
  "应用端口": "Application Port",
  "RestFul风格接口": "RESTful API",
  "包构建类型": "Packaging Type",
  "代码版本": "Code Version",
  "注释相关": "Comment Related",
  "开发人员": "Developer",
  "邮箱地址": "Email Address",
  "是否需要版权": "Need Copyright",
  "UI相关": "UI Related",
  "是否生成UI页面": "Generate UI Pages",
  "是否分离UI": "Separate UI",
  "Ui 文件后缀": "UI File Suffix",
  "UI 类型": "UI Type",
  "Dto相关": "DTO Related",
  "是否分离DTO": "Separate DTO",
  "目前只支持Java,选择其它语言会构建失败": "Currently only Java is supported, selecting other languages will cause build failure",
  "该属性为空表示生成所有数据库表的代码,如果表数量太多（>100），程序自动转异步执行，有构建失败风险.": "If this property is empty, code for all database tables will be generated. If there are too many tables (>100), the program will automatically switch to asynchronous execution, with a risk of build failure.",
  "如果该属性为空，所生成的文件会带上表前缀，eg: 表：dev_userinfo ,生成的文件是DevUserinfo.java;多个前缀请用英文分号（;）隔开。": "If this property is empty, the generated files will include the table prefix, e.g.: Table: dev_userinfo, generated file is DevUserinfo.java; multiple prefixes can be separated by semicolons (;).",
  "为空生成所有类型文件": "If empty, all types of files will be generated",
  "字段可见列数大于指定值时触发表单分组,默认不分组": "Trigger form grouping when the number of visible field columns exceeds the specified value, no grouping by default",
  "表单页面分组列数，默认2": "Number of form page group columns, default 2",
  "生成代码归属项目": "Generated Code Belonging Project",
  "Maven 项目的模块名会追加到包名的后面": "Maven project module name will be appended after the package name",
  "在配置文件application.yml中对应spring.application.name": "Corresponds to spring.application.name in the configuration file application.yml",
  "在配置文件application.yml中对应server.port": "Corresponds to server.port in the configuration file application.yml",
  "发布目录": "Publish Directory",
  "文件部署到服务器上的目录": "Directory where files are deployed on the server",
  "对应pom.xml文件中的packaging": "Corresponds to packaging in pom.xml",
  "对应pom.xml文件中version": "Corresponds to version in pom.xml",
  "UI文件和业务文件是否放在同一个module里面": "Whether UI files and business files are placed in the same module",
  "DTO文件和业务文件是否放在同一个module里面": "Whether DTO files and business files are placed in the same module",
  "流程校验": "Flow Validation",
  "错误": "Error",
  "警告": "Warning",
  "提示": "Info",
  "请假": "Leave",
  "报销": "Reimbursement",
  "聚餐": "Dinner",
  "请至少配置一个显示字段": "Please configure at least one display field",
  "容器设置": "Container Settings",
  "数据联动策略配置": "Data Linkage Strategy Configuration",
  "数据源配置": "Data Source Configuration",
  "请先选择要复制的组件": "Please select a component to copy first",
  "请先选择要剪切的组件": "Please select a component to cut first",
  "保存成功": "Save Successful",
  "保存失败": "Save Failed",
  "加载失败": "Load Failed",
  "获取列表失败": "Failed to Get List",
  "分享链接生成成功": "Share Link Generated Successfully",
  "分享失败": "Share Failed",
  "分享链接已失效或不存在": "Share Link Has Expired or Does Not Exist",
  "发布成功": "Published Successfully",
  "发布失败": "Publish Failed",
  "生成预览失败": "Preview Generation Failed",
  "删除成功": "Delete Successful",
  "删除失败": "Delete Failed",
  "复制成功": "Copy Successful",
  "复制失败": "Copy Failed",
};

// Output the translation map size
console.log(`Translation map size: ${Object.keys(translations).length}`);

// Write the translation map to a JSON file for verification
writeFileSync('e:/lixycode/dynamicform/src/lang/translation_map.json', JSON.stringify(translations, null, 2), 'utf-8');
console.log('Translation map written to translation_map.json');
