// 生成en_US.ts的脚本 - 基于zh_CN.ts的key-value对，生成对应的英文翻译
import { readFileSync, writeFileSync } from 'fs';

const zhContent = readFileSync('e:/lixycode/dynamicform/src/lang/zh_CN.ts', 'utf-8');

// 完整的中英文翻译映射表
const translationMap = {
  // starhorse
  "starhorse.copyright": "SPECIAL_VALUE:Config.footerTxt",
  "starhorse.pleaseInput": "Please input",
  "starhorse.pleaseSelect": "Please select",
  "starhorse.notAllowEmpty": "Cannot be empty",

  // home
  "home.addModule": "Add Module",
  "home.welcome": "Welcome to the System",
  "home.noModules": "You haven't configured any modules yet. Please add your first module.",
  "home.selectModule": "Select Module",
  "home.searchModules": "Search Modules...",
  "home.addSelectedModules": "Add Selected Modules",
  "home.category.all": "All",
  "home.category.system": "System Management",
  "home.category.business": "Business Modules",
  "home.category.analytics": "Data Analysis",
  "home.category.tools": "Tools",
  "home.module.userManagement": "User Management",
  "home.module.userManagementDesc": "Manage system users and permissions",
  "home.module.systemMonitor": "System Monitoring",
  "home.module.systemMonitorDesc": "View system running status",
  "home.module.personalCenter": "Personal Center",
  "home.module.personalCenterDesc": "View and edit personal information",
  "home.unreceived": "Unreceived",
  "home.processing": "Processing",
  "home.completed": "Completed",
  "home.following": "Following",
  "home.suspended": "Suspended",
  "home.delegated": "Delegated",
  "home.allWork": "All Work",
  "home.instructions1": "Click \"New Workflow\" to enter the new workflow page.",
  "home.instructions2": "Access urge and recall functions.",
  "home.allWorkDescription": "View all workflow tasks here.",
  "home.claimTask": "Claim Task",
  "home.completeTask": "Complete Task",
  "home.revokeTask": "Revoke Task",
  "home.unfollowTask": "Unfollow",
  "home.resumeTask": "Resume Task",
  "home.recallTask": "Recall Task",
  "home.task.claimed": "Task claimed",
  "home.task.completed": "Task completed",
  "home.task.revoked": "Task revoked",
  "home.task.unfollowed": "Unfollowed",
  "home.task.resumed": "Task resumed",
  "home.task.recalled": "Task recalled",
  "home.task.a": "Task approved",
  "home.task.b": "Task rejected",
  "home.task.c": "Task returned",
  "home.task.d": "Task returned to start",
  "home.task.e": "Task returned to historical task",
  "home.task.f": "Task revoked",
  "home.task.g": "Task transferred",
  "home.task.h": "Countersign added",
  "home.task.i": "Countersign removed",
  "home.task.j": "Task saved",
  "home.task.k": "Task terminated",
  "home.task.l": "Countersigned",
  "home.task.m": "Countersign approved",
  "home.task.n": "Countersign rejected",
  "home.task.o": "Countersign abstained",
  "home.task.p": "Approver assigned",
  "home.task.q": "Jump target assigned",

  // loginType
  "loginType.password": "Password Login",
  "loginType.rtCode": "Scan Code Login",
  "loginType.otherType": "Other Login Methods",
  "loginType.github": "GitHub",
  "loginType.wechat": "WeChat",
  "loginType.alipay": "Alipay",
  "loginType.weibo": "Weibo",
  "loginType.validCode": "Verification Code",

  // dyform.preOrPend
  "dyform.preOrPend.dialog.title": "Prefix/Suffix Configuration",
  "dyform.preOrPend.prependText": "Prefix Text",
  "dyform.preOrPend.prependText.helpMsg": "Fixed text displayed in front of the input box",
  "dyform.preOrPend.prependList": "Prefix Dropdown List",
  "dyform.preOrPend.prependList.helpMsg": "Configure dropdown options in front of the input box",
  "dyform.preOrPend.prependList.title": "Prefix Dropdown List Configuration",
  "dyform.preOrPend.appendText": "Suffix Text",
  "dyform.preOrPend.appendText.helpMsg": "Fixed text displayed after the input box",
  "dyform.preOrPend.appendAction": "Suffix Action Button",
  "dyform.preOrPend.appendAction.helpMsg": "Configure action buttons after the input box",
  "dyform.preOrPend.appendAction.title": "Suffix Action Button Configuration",
  "dyform.preOrPend.appendList": "Suffix Dropdown List",
  "dyform.preOrPend.appendList.helpMsg": "Configure dropdown options after the input box",
  "dyform.preOrPend.appendList.title": "Suffix Dropdown List Configuration",
  "dyform.preOrPend.warning.prependConflict": "Prefix text and prefix dropdown list cannot be configured simultaneously",
  "dyform.preOrPend.warning.appendConflict": "Suffix text, suffix action button and suffix dropdown list cannot be configured simultaneously",

  // login
  "login.userName": "Username",
  "login.password": "Password",
  "login.validCode": "Verification Code",
  "login.rememberMe": "Remember Me",
  "login.forget": "Forgot Password?",
  "login.noAccount": "No Account?",
  "login.remember.password": "Remember Password?",
  "login.forget.password.tip": "Please enter the email address you used when registering, and we will send a password reset link to that email.",

  // loginButton
  "loginButton.register": "Register Now",
  "loginButton.login": "Login",
  "loginButton.welcome": "Welcome",
  "loginButton.welcomeBack": "Welcome Back",
  "loginButton.description": "SPECIAL_TEMPLATE:loginButton.description",
  "loginButton.logging": "Logging in...",

  // userCenter
  "userCenter.checkEmailReset": "Please check your email and follow the instructions to reset your password.",

  // main.header
  "main.header.authority": "User Center",
  "main.header.calendar": "Calendar",
  "main.header.layoutConfig": "Layout Settings",
  "main.header.userEdit": "Edit Profile",
  "main.header.logout": "Logout",

  // dialog
  "dialog.cancel": "Cancel",
  "dialog.submit": "Submit",
  "dialog.submitContinue": "Submit & Continue",
  "dialog.save": "Save",
  "dialog.saveContinue": "Save & Continue",
  "dialog.reset": "Reset",
  "dialog.fullScreen": "Maximize",
  "dialog.resize": "Restore",
  "dialog.close": "Close",
  "dialog.addTitle": "Add Data",
  "dialog.batchAddTitle": "Batch Add Data",
  "dialog.interfaceError": "Interface does not exist or network error:",

  // flow
  "flow.design": "Flow Design",
  "flow.designer": "Flow Designer",
  "flow.designer.addNode": "Add Node",
  "flow.designer.addNode.start": "Start",
  "flow.designer.addNode.end": "End",
  "flow.designer.addNode.condition": "Condition Branch",
  "flow.designer.addNode.parallel": "Parallel Branch",
  "flow.designer.addNode.suggest": "Opinion Branch",
  "flow.designer.addNode.user": "User Node",
  "flow.designer.addNode.form": "Form Node",
  "flow.designer.addNode.approve": "Approval Node",
  "flow.designer.addNode.sign": "Countersign Node",
  "flow.designer.addNode.branch": "Branch Node",
  "flow.designer.addNode.loop": "Loop Node",
  "flow.designer.addNode.subProcess": "Sub Process Node",
  "flow.designer.addNode.auto": "Auto Node",
  "flow.designer.addNode.manual": "Manual Node",
  "flow.designer.addNode.autoApprove": "Auto Approve",
  "flow.designer.addNode.manualApprove": "Manual Approve",
  "flow.designer.addNode.autoSign": "Auto Countersign",
  "flow.designer.addNode.manualSign": "Manual Countersign",
  "flow.designer.addNode.autoBranch": "Auto Branch",
  "flow.designer.addNode.manualBranch": "Manual Branch",
  "flow.designer.addNode.autoLoop": "Auto Loop",
  "flow.designer.addNode.manualLoop": "Manual Loop",
  "flow.designer.addNode.autoSubProcess": "Auto Sub Process",
  "flow.designer.addNode.manualSubProcess": "Manual Sub Process",
  "flow.designer.delNode": "Delete Node",
  "flow.designer.delNode.confirm": "Confirm delete node?",
  "flow.designer.delNode.confirm.tips": "After deleting the node, all child nodes of this node will be deleted. Confirm?",

  // dyform designer
  "dyform.tab.component": "Components",
  "dyform.tab.dbinfo": "Data Source",
  "dyform.tab.charts": "Charts",
  "dyform.tab.template": "Templates",
  "dyform.tab.help": "Help",
  "dyform.collapse.layout": "Layout Components",
  "dyform.collapse.form": "Form Components",
  "dyform.collapse.custom": "Custom Components",
  "dyform.preview.validate.success": "Form validation passed",
  "dyform.preview.validate.failure": "Form validation failed, please check your input",
  "dyform.preview.html.title": "Form Preview",
  "dyform.preview.html.export.success": "HTML file exported successfully",
  "dyform.preview.button.validate": "Validate Form",
  "dyform.preview.button.export": "Export HTML",
  "dyform.preview.dialog.title": "Form Preview",
  "dyform.field.layer.title": "Form Property Layer",
  "dyform.field.list.title": "Form List",
  "dyform.designer.welcome": "Welcome to Form Designer",
  "dyform.designer.instruction": "Please select a component from the left component library, then double-click or drag the component to place it here",
  "dyform.designer.tip.drag": "Drag Components",
  "dyform.designer.tip.config": "Configure Properties",
  "dyform.designer.tip.build": "Quick Build",
  "dyform.toolbar.cache.restore": "Restore Cached Data",
  "dyform.action.goBack": "Back to List",
  "dyform.action.style": "Style",
  "dyform.action.pc": "PC",
  "dyform.action.pad": "Tablet",
  "dyform.action.phone": "Mobile",
  "dyform.action.new": "New",
  "dyform.action.import": "Import",
  "dyform.action.export": "Export",
  "dyform.action.edit": "Edit Properties",
  "dyform.action.layer": "Form Layer",
  "dyform.action.empty": "Clear Elements",
  "dyform.action.undo": "Undo",
  "dyform.action.redo": "Redo",
  "dyform.action.valid": "Validate",
  "dyform.action.preview": "Preview",
  "dyform.action.code": "Generate Code",
  "dyform.action.save": "Save",
  "dyform.help.title": "Help",
  "dyform.batch.edit.title": "Batch Edit Properties",
  "dyform.batch.edit.tab.business": "Business Fields",
  "dyform.batch.edit.tab.common": "Common Fields",
  "dyform.button.event.title": "Button Click Event",
  "dyform.template.load": "Load This Template",

  // dyform help
  "dyform.help.shortcuts": "Shortcuts",
  "dyform.help.shortcut.cut": "Cut",
  "dyform.help.shortcut.copy": "Copy",
  "dyform.help.shortcut.paste": "Paste",
  "dyform.help.shortcut.undo": "Undo",
  "dyform.help.shortcut.redo": "Redo",
  "dyform.help.shortcut.validate": "Validate",
  "dyform.help.shortcut.new": "New",
  "dyform.help.shortcut.save": "Save",
  "dyform.help.shortcut.delete": "Delete",
  "dyform.help.shortcut.selectAll": "Select All",
  "dyform.help.shortcut.clear": "Clear",
  "dyform.help.shortcut.find": "Find",
  "dyform.help.shortcut.toggleLeftPanel": "Open/Close Left Panel",
  "dyform.help.shortcut.toggleRightPanel": "Open/Close Right Panel",
  "dyform.help.shortcut.changeComponent": "Change Selected Component",
  "dyform.help.shortcut.preview": "Preview",
  "dyform.help.shortcut.goBack": "Go Back to Previous Page",
  "dyform.help.shortcut.moveUp": "Move Selected Component Up",
  "dyform.help.shortcut.moveDown": "Move Selected Component Down",
  "dyform.help.moreShortcuts": "More shortcuts to be updated",
  "dyform.help.description": "Description",
  "dyform.help.designerDescription": "Form Designer is a tool that can implement complex form models through drag and drop, which can meet most common business needs",
  "dyform.help.rules": "Rules",
  "dyform.help.rule1": "All sibling component names cannot be duplicated. In Tab components, tabName and objectName cannot be duplicated",
  "dyform.help.rule2": "In Table components, batchFieldName cannot be duplicated",
  "dyform.help.steps": "Steps",
  "dyform.help.step1": "Drag or double-click components on the left to add them to the middle design stage",
  "dyform.help.step2": "Set properties of selected components in the right property area",
  "dyform.help.step3": "Use the batch edit button in the header to edit property names",
  "dyform.help.step4": "Use the settings button in the header to set form properties",
  "dyform.help.step5": "Use the code button in the header to generate code (currently only Vue3)",
  "dyform.help.step6": "Use the preview button in the header to preview form information",
  "dyform.help.step7": "Right-click on the stage to open the context menu",
  "dyform.help.blindSpots": "Blind Spots (Form models generated by data sources)",
  "dyform.help.blindSpot1": "Note the value types of selector, radio box, checkbox and other components. The system default is string type. If the database setting is numeric type, you need to modify the value type in the corresponding field's property panel",
  "dyform.help.blindSpot2": "When submitting, pay attention to the primary key generation strategy of the table. The default is dynamic assignment. If it is auto-increment, you need to modify the primary key strategy when saving",
  "dyform.help.notImplemented": "Not Implemented",
  "dyform.batch.edit.commonFieldsMessage": "Set in configuration or submission function",
  "dyform.config.dialog.title": "Form Configuration",
  "dyform.config.draft.save": "Save Draft",
  "dyform.code.dialog.title": "Code",

  // dyform js editor
  "dyform.js.editor.title": "Custom Information",
  "dyform.js.editor.customEvent": "Custom events provide the following system parameters",
  "dyform.js.editor.currentFieldInfo": "Current component information",
  "dyform.js.editor.formData": "Form Data",
  "dyform.js.editor.formElements": "All form elements",
  "dyform.js.editor.formInstance": "Form Instance Object",
  "dyform.js.editor.parametersMethods": "Switch tabs to view specific parameters or methods",
  "dyform.js.editor.tab.code": "Code",
  "dyform.js.editor.tab.currentField": "Current Component Properties",
  "dyform.js.editor.tab.formInstance": "Form Instance",
  "dyform.js.editor.tab.formProperties": "Form Properties",
  "dyform.js.editor.objectName": "Object Name",
  "dyform.js.editor.table.name": "Name",
  "dyform.js.editor.table.description": "Description",
  "dyform.js.editor.table.type": "Type",
  "dyform.js.editor.formInstance.validate": "Validate the contents of the entire form. Receives a callback function, or returns",
  "dyform.js.editor.formInstance.validateField": "Validate a specific field.",
  "dyform.js.editor.formInstance.resetFields": "Reset the form item, reset its value to the initial value, and remove the validation result",
  "dyform.js.editor.formInstance.scrollToField": "Scroll to the specified field",
  "dyform.js.editor.formInstance.clearValidate": "Clear form validation information for a field.",
  "dyform.js.editor.formInstance.fields": "Get context of all fields",

  // dyform params
  "dyform.params.dialog.title": "Parameter Configuration",
  "dyform.params.warning.primaryKey": "Please select the primary key field",
  "dyform.params.warning.callbackFields": "Please configure callback fields",
  "dyform.params.warning.displayFields": "Please configure at least one display field",

  // mindmap
  "mindmap.root.node": "Root Node",
  "mindmap.cooperate.plugin": "Cooperate Plugin",

  // workflow
  "workflow.process.name": "Process Name",
  "workflow.process.category": "Process Category",
  "workflow.is.deployed": "Is Deployed",
  "workflow.deployed": "Deployed",
  "workflow.not.deployed": "Not Deployed",
  "workflow.flow.deployment.id": "Flow Deployment ID",
  "workflow.bind.form.info": "Bind Form Info",
  "workflow.flow.icon": "Icon",
  "workflow.flow.type": "Flow Type",
  "workflow.status": "Status",
  "workflow.flow.version": "Flow Version",
  "workflow.form.visible.type": "Multi-form Display Mode",
  "workflow.flow.manager": "Flow Manager",
  "workflow.flow.xml.file": "Flow XML File",
  "workflow.flow.json.file": "Flow JSON File",
  "workflow.version.number": "Version Number",
  "workflow.is.deleted": "Is Deleted",
  "workflow.data.number": "Data Number",
  "workflow.status.name": "Status Name",
  "workflow.international.code": "International Code",
  "workflow.remark": "Remark",
  "workflow.edit": "Edit",
  "workflow.view": "View",
  "workflow.add": "Add",
  "workflow.config.category": "Config Category",
  "workflow.name": "Name",
  "workflow.code": "Code",
  "workflow.is.checked": "Is Checked",
  "workflow.yes": "Yes",
  "workflow.no": "No",
  "workflow.image.url": "Image URL",
  "workflow.description": "Description",
  "workflow.suspended.by": "{user} suspended the task",
  "workflow.delegated.to": "Task delegated to {user}",
  "workflow.in.process": "In Process",
  "workflow.initiator": "Initiator",
  "workflow.approval.node": "Approval Node",
  "workflow.final.approval": "Final Approval",
  "workflow.submitted.by": "{user} submitted the application",
  "workflow.pending.approval": "Pending Approval",
  "workflow.approved.by": "{user} approved",
  "workflow.pending.assignee": "Pending Claim",
  "workflow.current.assignee": "Current Handler",
  "workflow.not.started": "Not Started",

  // continuous
  "continuous.node": "Node",
  "continuous.report.type": "Test Report Type",
  "continuous.primary.key": "Primary Key",
  "continuous.instance.id": "Instance ID",
  "continuous.node.name": "Name",
  "continuous.column.index": "Column Index",
  "continuous.execution.type": "Execution Type",
  "continuous.program.language": "Program Language",
  "continuous.project.code": "Project Code",
  "continuous.source.code.dir": "Source Code Directory",
  "continuous.failure.notification": "Failure Notification",
  "continuous.success.notification": "Success Notification",
  "continuous.custom.rules": "Custom Rules",
  "continuous.row.index": "Row Index",
  "continuous.project.name": "Project Name",
  "continuous.project.type": "Project Type",
  "continuous.instance.name": "Instance Name",
  "continuous.template": "Template",
  "continuous.is.alone": "Is Exclusive (1=Yes, 2=No, Default=2)",
  "continuous.link.data.plan": "Linked Plan",
  "continuous.cron": "Cron Scheduled Execution",
  "continuous.target.dir": "Code Download Directory",
  "continuous.auto.build": "Auto Build (1=Yes, 2=No, Default=2)",
  "continuous.remark": "Remark",
  "continuous.created.by": "Created By",
  "continuous.updated.by": "Updated By",
  "continuous.created.date": "Created Date",
  "continuous.updated.date": "Updated Date",
  "continuous.data.version": "Data Version",
  "continuous.is.deleted": "Is Logically Deleted",
  "continuous.data.number": "Data Number",
  "continuous.status.code": "Status Code",
  "continuous.status.name": "Status Name",
  "continuous.international.code": "International Code",

  // project info
  "project.info.repo.type": "Repository Type",
  "project.info.repo.url": "Repository URL",
  "project.info.program.language": "Program Language",
  "project.info.project.name": "Project Name",
  "project.info.project.charset": "Project Charset",
  "project.info.line.account": "Pipeline Account",
  "project.info.line.security": "Pipeline Password",
  "project.info.remark": "Remark",
  "project.info.project.members": "Project Members",
  "project.info.username": "Username",
  "project.info.name": "Name",
  "project.info.employee.no": "Employee No",
  "project.info.rank": "Rank",
  "project.info.station": "Position",
  "project.info.role.name": "Role Name",
  "project.info.effective.date": "Effective Date",
  "project.info.expiration.date": "Expiration Date",
  "project.info.is.manager": "Is Manager",
  "project.info.yes": "Yes",
  "project.info.no": "No",

  // system
  "system.name": "Name",
  "system.username": "Username",
  "system.user.group": "User Group",
  "system.cannot.set.empty.password": "Cannot set empty password",
  "system.password.length": "Please set a password with length between 6 and 15",
  "system.password.mismatch": "Passwords do not match, please re-enter",
  "system.employee.no": "Employee No",
  "system.password": "Password",
  "system.confirm.password": "Confirm Password",
  "system.change.password": "Change Password",
  "system.area.name": "Area Name",
  "system.area.code": "Area Code",
  "system.area.key": "Area Key",
  "system.parent.node.number": "Parent Node Number",
  "system.request.method": "Request Method",
  "system.operator": "Operator",
  "system.access.interface": "Access Interface",
  "system.access.address": "Access Address",
  "system.primary.key": "Primary Key",
  "system.request.parameters": "Request Parameters",
  "system.created.by": "Created By",
  "system.updated.by": "Updated By",
  "system.created.date": "Created Date",
  "system.updated.date": "Updated Date",
  "system.completed.date": "Completed Date",
  "system.suspended.date": "Suspended Date",
  "system.delegated.date": "Delegated Date",
  "system.cancel": "Cancel",
  "system.confirm": "Confirm",
  "system.auditing.opinion": "Approval Opinion",
  "system.data.version": "Data Version",
  "system.is.deleted": "Is Logically Deleted",
  "system.data.number": "Data Number",
  "system.status.code": "Status",
  "system.status.name": "Status Name",
  "system.international.code": "International Code",
  "system.interface.address": "Interface Address",
  "system.remark": "Remark",
  "system.customer.name": "Customer Name",
  "system.customer.code": "Customer Code",
  "system.logo": "Logo",
  "system.description": "Description",
  "system.created.time": "Created Time",
  "system.updated.time": "Updated Time",
  "system.version": "Version",
  "system.is.logical.deleted": "Is Logically Deleted",
  "system.department.name": "Department Name",
  "system.department.code": "Department Code",
  "system.parent.department": "Parent Department",
  "system.department.leader": "Department Leader",
  "system.division.leader": "Division Leader",
  "system.affiliated.company": "Affiliated Company",
  "system.department.phone": "Department Phone",
  "system.department.responsibility": "Department Responsibility",
  "system.code": "Code",
  "system.dictionary.type.name": "Dictionary Type Name",
  "system.dictionary.type.code": "Dictionary Type Code",
  "system.dictionary.type": "Dictionary Type",
  "system.dictionary.name": "Dictionary Name",
  "system.dictionary.code": "Dictionary Code",
  "system.sort": "Sort",
  "system.status": "Status",
  "system.dictionary.description": "Dictionary Description",
  "system.dictionary.info": "Dictionary Info",
  "system.edit": "Edit",
  "system.please.select.dictionary.category": "Please select dictionary category first",
  "system.belonging.entity": "Belonging Entity",
  "system.application.name": "Application Name",
  "system.add.time": "Add Time",
  "system.parent.application": "Parent Application",
  "system.system.code": "System Code",
  "system.system.logo": "System Logo",
  "system.data.sort": "Data Sort",
  "system.system.description": "System Description",
  "system.menu.name": "Menu Name",
  "system.menu.code": "Menu Code",
  "system.menu.icon": "Menu Icon",
  "system.menu.description": "Menu Description",
  "system.original.application": "Original Application",
  "system.new.application": "New Application",
  "system.new.application.parent.menu": "Parent Menu of New Application",
  "system.open.type": "Open Type",
  "system.keep.alive": "Keep Alive",
  "system.menu.switch.method": "Menu Switch Method",
  "system.move": "Move",
  "system.copy": "Copy",
  "system.menu.list": "Menu List",
  "system.original.application.menu": "Original Application Menu",
  "system.target.application.menu": "Target Application Menu",
  "system.return.to.left": "Return to Left",
  "system.add.to.right": "Add to Right",
  "system.menu.path": "Menu Path",
};

// 由于映射表太大，我将直接生成完整的en_US.ts文件
console.log("Translation map initialized with", Object.keys(translationMap).length, "entries");
console.log("This script is a helper - the main en_US.ts will be generated directly");
