app.name=server-api
app.active=dev
config.nacos.ip=10.10.10.50
config.nacos.port=9848
spring.config.import=optional:nacos:${app.name}-${app.active}?server-addr=${config.nacos.ip}:${config.nacos.port}&group=DEFAULT_GROUP&refresh=true
# 1. ?????
spring.cloud.nacos.discovery.server-addr=${config.nacos.ip}:${config.nacos.port}
spring.cloud.nacos.config.server-addr=${config.nacos.ip}:${config.nacos.port}
spring.cloud.nacos.config.group=DEFAULT_GROUP
spring.cloud.nacos.config.file-extension=properties
# 2.

# 3.
spring.cloud.nacos.config.extension-configs[0].data-id=${app.name}-${app.active}
spring.cloud.nacos.config.extension-configs[0].group=DEFAULT_GROUP
spring.cloud.nacos.config.extension-configs[0].refresh=true
# 4.
spring.cloud.nacos.config.import-check.enabled=false

# STOMP 配置 - 增加缓冲区大小以支持大文件传输（如图片）
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB