const javaKeywords = [
    {label: "public", apply: "public "},
    {label: "private", apply: "private "},
    {label: "protect", apply: "protect "},
    {label: "sout", apply: "System.out.println();"},
    {label: "main", apply: "public void main(String[] args){\n}"},
    {label: "psfs", apply: "public static final String "},
    {label: "psfi", apply: "public static final Integer "},
    {label: "psfd", apply: "public static final Double "},
    {label: "class", apply: "class "},
    {label: "package", apply: "package "},
    {label: "import", apply: "import "},
    {label: "int", apply: "int "},
    {label: "Integer", apply: "Integer "},
    {label: "long", apply: "long "},
    {label: "Long", apply: "Long "},
    {label: "Long", apply: "Long "},
    {label: "short", apply: "hort "},
    {label: "Short", apply: "Short "},
    {label: "Byte", apply: "Byte "},
    {label: "byte", apply: "byte "},
    {label: "float", apply: "float "},
    {label: "Float", apply: "Float "},
    {label: "Return", apply: "Return "},
    {label: "small", apply: "default "},
    {label: "switch", apply: "switch "},
    {label: "forin", apply: "for in {\n}"},
    {label: "foreach", apply: "forEach(item->{\n});"}
];
export {javaKeywords};
