import { CompType, SelectOption } from "star-horse-lowcode";
import {i18n} from "@/lang";

const commonSelectOptions: SelectOption[] = [
  { name: i18n("dyform.item.40"), value: "string" },
  { name: i18n("dyform.item.41"), value: "number" },
];
export const formExtendItems: CompType[] = [
  {
    itemName: i18n("dyform.extend.346"),
    itemType: "page-select",
    itemIcon: "input",
    category: 3,
    fields: [
      {
        label: i18n("dyform.item.39"),
        fieldName: "valueType",
        fieldType: "select",
        required: false,
        selectValues: commonSelectOptions,
        defaultValues: "",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.347"),
        fieldName: "paramConfig",
        fieldType: "config",
        required: true,
        selectValues: "",
        defaultValues: "",
        category: 1,
        configParams: [],
      },
    ],
    advancedFields: [
      {
        label: i18n("dyform.extend.348"),
        fieldName: "needField",
        fieldType: "json",
        required: true,
        selectValues: "",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.349"),
        fieldName: "dataUrl",
        fieldType: "input",
        required: true,
        selectValues: "",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: i18n("dyform.item.7"),
        fieldName: "placeholder",
        fieldType: "input",
        required: false,
        selectValues: "",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.350"),
        fieldName: "fieldList",
        fieldType: "json",
        required: false,
        selectValues: "",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.351"),
        fieldName: "condition",
        fieldType: "json",
        required: false,
        selectValues: "",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.352"),
        fieldName: "orderby",
        fieldType: "json",
        required: false,
        selectValues: "",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
    ],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.extend.353"),
    itemType: "dialog-input",
    itemIcon: "input",
    category: 3,
    fields: [
      {
        label: i18n("dyform.extend.347"),
        fieldName: "paramConfig",
        fieldType: "config",
        required: true,
        selectValues: "",
        defaultValues: "",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.item.39"),
        fieldName: "valueType",
        fieldType: "select",
        required: false,
        selectValues: commonSelectOptions,
        defaultValues: "",
        category: 1,
        configParams: [],
      },
    ],
    advancedFields: [
      {
        label: i18n("dyform.extend.348"),
        fieldName: "needField",
        fieldType: "json",
        required: true,
        selectValues: "",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.350"),
        fieldName: "fieldList",
        fieldType: "json",
        required: false,
        selectValues: "",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.352"),
        fieldName: "orderby",
        fieldType: "json",
        required: false,
        selectValues: "",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: i18n("dyform.item.7"),
        fieldName: "placeholder",
        fieldType: "input",
        required: false,
        selectValues: "",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: "Style",
        fieldName: "inputStyle",
        fieldType: "input",
        required: false,
        selectValues: "",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
    ],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: "Crontab",
    itemType: "cron",
    itemIcon: "crontab",
    category: 3,
    fields: [],
    advancedFields: [
      {
        label: i18n("dyform.item.126"),
        fieldName: "autosize",
        fieldType: "switch",
        required: false,
        selectValues: "[true,false]",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: i18n("dyform.item.7"),
        fieldName: "placeholder",
        fieldType: "input",
        required: false,
        selectValues: "",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.354"),
        fieldName: "size",
        fieldType: "select",
        required: false,
        selectValues: [
          { name: i18n("dyform.extend.355"), value: "large" },
          { name: i18n("dyform.item.289"), value: "default" },
          { name: i18n("dyform.extend.356"), value: "small" },
        ],
        defaultValues: "",
        category: 2,
        configParams: [],
      },
    ],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.extend.357"),
    itemType: "relation-select",
    itemIcon: "input",
    category: 3,
    fields: [
      {
        label: i18n("dyform.item.39"),
        fieldName: "valueType",
        fieldType: "select",
        required: false,
        selectValues: commonSelectOptions,
        defaultValues: "",
        category: 1,
        configParams: [],
      },
    ],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },

  {
    itemName: i18n("dyform.extend.358"),
    itemType: "area",
    itemIcon: "text",
    category: 3,
    fields: [
      {
        label: i18n("dyform.extend.359"),
        fieldName: "filterable",
        fieldType: "switch",
        required: false,
        selectValues: "[true,false]",
        defaultValues: "",
        category: 1,
        configParams: [],
      },
    ],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.extend.360"),
    itemType: "vedio",
    itemIcon: "vedio",
    category: 3,
    fields: [],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: "JSON",
    itemType: "json",
    itemIcon: "text",
    category: 3,
    fields: [
      {
        label: i18n("dyform.extend.361"),
        fieldName: "devType",
        fieldType: "switch",
        required: false,
        selectValues: "[true,false]",
        defaultValues: "",
        category: 1,
        configParams: [],
      },
    ],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.extend.362"),
    itemType: "audio",
    itemIcon: "audio",
    category: 3,
    fields: [],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: "MarkDown",
    itemType: "markdown",
    itemIcon: "text",
    category: 3,
    fields: [],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.extend.363"),
    itemType: "signature",
    itemIcon: "text",
    category: 3,
    fields: [
      {
        label: i18n("dyform.item.120"),
        fieldName: "width",
        required: false,
        fieldType: "number",
        defaultValues: "350",
        category: 1,
      },
      {
        label: i18n("dyform.item.261"),
        fieldName: "height",
        required: false,
        fieldType: "number",
        defaultValues: "100",
        category: 1,
      },
      {
        label: i18n("dyform.extend.364"),
        fieldName: "minWidth",
        required: false,
        fieldType: "number",
        defaultValues: "2",
        category: 1,
      },
      {
        label: i18n("dyform.extend.365"),
        fieldName: "minWidth",
        required: false,
        fieldType: "number",
        defaultValues: "6",
        category: 1,
      },
    ],
    advancedFields: [
      {
        label: i18n("dyform.extend.366"),
        fieldName: "openSmooth",
        required: false,
        fieldType: "switch",
        defaultValues: true,
        category: 2,
      },
      {
        label: i18n("dyform.extend.367"),
        fieldName: "minWidth",
        required: false,
        helpMsg:
          i18n("dyform.extend.368"),
        fieldType: "number",
        defaultValues: "1.5",
        category: 2,
      },
    ],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.extend.369"),
    itemType: "json-array",
    itemIcon: "text",
    category: 3,
    fields: [
      {
        label: i18n("dyform.extend.361"),
        fieldName: "devType",
        fieldType: "switch",
        required: false,
        selectValues: "[true,false]",
        defaultValues: "",
        category: 1,
        configParams: [],
      },
    ],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },

  {
    itemName: i18n("dyform.extend.370"),
    itemType: "usercomp",
    itemIcon: "setting",
    category: 3,
    fields: [
      {
        label: i18n("dyform.item.0"),
        fieldName: "compName",
        fieldType: "input",
        required: true,
        selectValues: "",
        defaultValues: "",
        category: 1,
        remark: i18n("dyform.extend.371"),
        configParams: [],
      },
      {
        label: i18n("dyform.extend.372"),
        fieldName: "compDirName",
        fieldType: "input",
        required: false,
        selectValues: "",
        defaultValues: "",
        category: 1,
        remark: "",
        configParams: [],
      },
    ],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.extend.373"),
    itemType: "qrcode",
    itemIcon: "qrcode",
    category: 3,
    fields: [
      {
        label: i18n("dyform.extend.374"),
        fieldName: "color",
        fieldType: "input",
        required: false,
        selectValues: "",
        defaultValues: "#000",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.375"),
        fieldName: "size",
        fieldType: "input",
        required: false,
        selectValues: "",
        defaultValues: "160",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.item.155"),
        fieldName: "bgColor",
        fieldType: "input",
        required: false,
        selectValues: "",
        defaultValues: "#fff",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.376"),
        fieldName: "level",
        fieldType: "select",
        required: false,
        selectValues: [
          { name: i18n("dyform.extend.377"), value: "L" },
          { name: i18n("dyform.item.289"), value: "M" },
          { name: "1/4", value: "Q" },
          { name: i18n("dyform.extend.378"), value: "H" },
        ],
        defaultValues: "M",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.379"),
        fieldName: "status",
        fieldType: "select",
        required: false,
        selectValues: [
          { name: i18n("dyform.extend.380"), value: "active" },
          { name: i18n("dyform.extend.381"), value: "expired" },
          { name: i18n("dyform.extend.382"), value: "loading" },
          { name: i18n("dyform.extend.383"), value: "scanned" },
        ],
        defaultValues: "active",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.384"),
        fieldName: "type",
        fieldType: "select",
        required: false,
        selectValues: [
          { name: "Canvas", value: "canvas" },
          { name: "Svg", value: "svg" },
        ],
        defaultValues: "svg",
        category: 1,
        configParams: [],
      },
    ],
    advancedFields: [
      {
        label: i18n("dyform.extend.385"),
        fieldName: "icon",
        fieldType: "input",
        required: false,
        selectValues: "",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.386"),
        fieldName: "iconSize",
        fieldType: "input",
        required: false,
        selectValues: "",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.387"),
        fieldName: "iconsettings",
        fieldType: "json",
        required: false,
        selectValues: "",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
    ],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.extend.388"),
    itemType: "barcode",
    itemIcon: "date-range-field",
    category: 3,
    fields: [
      {
        label: i18n("dyform.item.9"),
        fieldName: "scale",
        fieldType: "input",
        required: false,
        selectValues: "",
        defaultValues: "3",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.389"),
        fieldName: "includeText",
        fieldType: "switch",
        required: false,
        selectValues: "",
        defaultValues: "true",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.item.261"),
        fieldName: "height",
        fieldType: "input",
        required: false,
        selectValues: "",
        defaultValues: "10",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.390"),
        fieldName: "textAlign",
        fieldType: "select",
        required: false,
        selectValues: [
          { name: i18n("dyform.item.32"), value: "left" },
          { name: i18n("dyform.item.289"), value: "center" },
          { name: i18n("dyform.item.33"), value: "right" },
        ],
        defaultValues: "center",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.extend.391"),
        fieldName: "bcid",
        fieldType: "input",
        required: false,
        selectValues: "",
        defaultValues: "code128",
        category: 1,
        configParams: [],
      },
    ],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.extend.392"),
    itemType: "area",
    itemIcon: "position",
    category: 3,
    fields: [],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.extend.393"),
    itemType: "datapicker",
    itemIcon: "select",
    category: 3,
    fields: [],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },
];
