import { CompType } from "star-horse-lowcode";
import {i18n} from "@/lang";

export const formContainer: CompType[] = [
  {
    itemName: i18n("dyform.container.312"),
    itemType: "box",
    itemIcon: "box",
    category: 2,
    remark: i18n("dyform.container.313"),
    fields: [
      {
        label: i18n("dyform.container.314"),
        fieldName: "align",
        fieldType: "select",
        required: false,
        selectValues: [
          { name: i18n("dyform.item.47"), value: "top" },
          { name: i18n("dyform.container.315"), value: "middle" },
          { name: i18n("dyform.item.50"), value: "bottom" },
        ],
        defaultValues: "",
        category: 1,
        configParams: [],
      },
    ],
    advancedFields: [
      {
        label: i18n("dyform.container.316"),
        fieldName: "justify",
        fieldType: "select",
        required: false,
        selectValues: [
          { name: "Start", value: "start" },
          { name: "End", value: "end" },
          { name: "Center", value: "center" },
          { name: "SpaceAround", value: "space-around" },
          { name: "SpaceBetween", value: "space-between" },
          { name: "SpaceEvenly", value: "space-evenly" },
        ],
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: i18n("dyform.container.317"),
        fieldName: "gutter",
        fieldType: "number",
        required: false,
        selectValues: "0",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: i18n("dyform.container.318"),
        fieldName: "tag",
        fieldType: "input",
        required: false,
        selectValues: "div",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
    ],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: "Tab",
    itemType: "tab",
    itemIcon: "tab",
    category: 2,
    fields: [
      {
        label: i18n("dyform.container.319"),
        fieldName: "stretch",
        fieldType: "switch",
        required: false,
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.container.320"),
        fieldName: "editable",
        fieldType: "switch",
        required: false,
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.container.321"),
        fieldName: "addable",
        fieldType: "switch",
        required: false,
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.container.322"),
        fieldName: "tablePosition",
        fieldType: "select",
        required: false,
        selectValues: [
          { name: i18n("dyform.item.47"), value: "top" },
          { name: i18n("dyform.container.323"), value: "right" },
          { name: i18n("dyform.item.50"), value: "bottom" },
          { name: i18n("dyform.container.324"), value: "left" },
        ],
        defaultValues: "",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.container.325"),
        fieldName: "type",
        fieldType: "select",
        required: false,
        selectValues: [
          { name: i18n("dyform.item.267"), value: "—" },
          { name: i18n("dyform.container.326"), value: "card" },
          { name: i18n("dyform.container.327"), value: "border-card" },
        ],
        defaultValues: "",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.container.328"),
        fieldName: "closable",
        fieldType: "switch",
        required: false,
        category: 1,
        configParams: [],
      },
    ],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.container.329"),
    itemType: "table",
    itemIcon: "table",
    category: 2,
    fields: [
      {
        label: i18n("dyform.container.330"),
        fieldName: "label",
        fieldType: "input",
        required: true,
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.container.331"),
        fieldName: "templateDownFlag",
        fieldType: "switch",
        required: false,
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.container.332"),
        fieldName: "importFlag",
        fieldType: "switch",
        required: false,
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.container.333"),
        fieldName: "subFormFlag",
        fieldType: "switch",
        required: false,
        defaultValues: true,
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.container.334"),
        fieldName: "primaryKeyName",
        fieldType: "input",
        required: true,
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.container.335"),
        fieldName: "batchFieldName",
        fieldType: "input",
        required: true,
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.container.336"),
        fieldName: "columns",
        fieldType: "number",
        required: false,
        selectValues: "1",
        defaultValues: "",
        category: 1,
        configParams: [],
      },
    ],
    advancedFields: [
      {
        label: i18n("dyform.container.337"),
        fieldName: "gutter",
        fieldType: "number",
        required: false,
        selectValues: "0",
        defaultValues: "",
        category: 2,
        configParams: [],
      },
      {
        label: i18n("dyform.container.338"),
        fieldName: "align",
        fieldType: "select",
        required: false,
        selectValues: [
          { name: i18n("dyform.item.47"), value: "top" },
          { name: i18n("dyform.container.315"), value: "middle" },
          { name: i18n("dyform.item.50"), value: "bottom" },
        ],
        defaultValues: "",
        category: 2,
        configParams: [],
      },
    ],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.container.339"),
    itemType: "collapse",
    itemIcon: "text",
    category: 2,
    fields: [],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.container.326"),
    itemType: "card",
    itemIcon: "text",
    category: 2,
    fields: [],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.container.340"),
    itemType: "dytable",
    itemIcon: "text",
    category: 2,
    fields: [
      {
        label: i18n("dyform.container.341"),
        fieldName: "rowSpan",
        fieldType: "input",
        required: false,
        selectValues: "",
        defaultValues: "",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.container.342"),
        fieldName: "colSpan",
        fieldType: "input",
        required: false,
        selectValues: "",
        defaultValues: "",
        category: 1,
        configParams: [],
      },
    ],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.container.343"),
    itemType: "splitter",
    itemIcon: "text",
    category: 2,
    fields: [
      {
        label: i18n("dyform.container.344"),
        fieldName: "lazy",
        fieldType: "switch",
        required: false,
        selectValues: "",
        defaultValues: "false",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.container.345"),
        fieldName: "layout",
        fieldType: "select",
        required: false,
        selectValues: [
          { name: i18n("dyform.item.291"), value: "horizontal" },
          { name: i18n("dyform.item.292"), value: "vertical" },
        ],
        defaultValues: "horizontal",
        category: 1,
        configParams: [],
      },
    ],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },
  {
    itemName: i18n("dyform.condition.containerName"),
    itemType: "condition",
    itemIcon: "condition",
    category: 2,
    remark: i18n("dyform.condition.containerRemark"),
    fields: [
      {
        label: i18n("dyform.condition.label"),
        fieldName: "label",
        fieldType: "input",
        required: false,
        defaultValues: "",
        category: 1,
        configParams: [],
      },
      {
        label: i18n("dyform.condition.placeholder"),
        fieldName: "placeholder",
        fieldType: "input",
        required: false,
        defaultValues: "",
        category: 1,
        configParams: [],
      },
    ],
    advancedFields: [],
    selfFields: [],
    actions: [],
    preps: [],
  },
];
