import {CompType, SelectOption} from "star-horse-lowcode";

const commonSelectOptions: SelectOption[] = [
    {name: "字符串", value: "string"},
    {name: "数值", value: "number"},
];
export const formExtendItems: CompType[] = [
    {
        itemName: "下拉分页",
        itemType: "page-select",
        itemIcon: "input",
        category: 3,
        fields: [
            {
                label: "值类型",
                fieldName: "valueType",
                fieldType: "select",
                required: false,
                selectValues: commonSelectOptions,
                defaultValues: "",
                category: 1,
                configParams: [],
            },
            {
                label: "参数配置",
                fieldName: "paramConfig",
                fieldType: "config",
                required: true,
                selectValues: "",
                defaultValues: "",
                category: 1,
                configParams: [],
            },
        ],
        advancedFields: [
            {
                label: "指定返回字段",
                fieldName: "needField",
                fieldType: "json",
                required: true,
                selectValues: "",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
            {
                label: "接口地址",
                fieldName: "dataUrl",
                fieldType: "input",
                required: true,
                selectValues: "",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
            {
                label: "占位信息",
                fieldName: "placeholder",
                fieldType: "input",
                required: false,
                selectValues: "",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
            {
                label: "展示字段",
                fieldName: "fieldList",
                fieldType: "json",
                required: false,
                selectValues: "",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
            {
                label: "查询条件",
                fieldName: "condition",
                fieldType: "json",
                required: false,
                selectValues: "",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
            {
                label: "排序",
                fieldName: "orderby",
                fieldType: "json",
                required: false,
                selectValues: "",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
        ],
        selfFields: [],
        actions: [],
        preps: [],
    },
    {
        itemName: "弹窗选择",
        itemType: "dialog-input",
        itemIcon: "input",
        category: 3,
        fields: [
            {
                label: "参数配置",
                fieldName: "paramConfig",
                fieldType: "config",
                required: true,
                selectValues: "",
                defaultValues: "",
                category: 1,
                configParams: [],
            },
            {
                label: "值类型",
                fieldName: "valueType",
                fieldType: "select",
                required: false,
                selectValues: commonSelectOptions,
                defaultValues: "",
                category: 1,
                configParams: [],
            },
        ],
        advancedFields: [
            {
                label: "指定返回字段",
                fieldName: "needField",
                fieldType: "json",
                required: true,
                selectValues: "",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
            {
                label: "展示字段",
                fieldName: "fieldList",
                fieldType: "json",
                required: false,
                selectValues: "",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
            {
                label: "排序",
                fieldName: "orderby",
                fieldType: "json",
                required: false,
                selectValues: "",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
            {
                label: "占位信息",
                fieldName: "placeholder",
                fieldType: "input",
                required: false,
                selectValues: "",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
            {
                label: "Style",
                fieldName: "inputStyle",
                fieldType: "input",
                required: false,
                selectValues: "",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
        ],
        selfFields: [],
        actions: [],
        preps: [],
    },
    {
        itemName: "Crontab",
        itemType: "cron",
        itemIcon: "crontab",
        category: 3,
        fields: [],
        advancedFields: [
            {
                label: "高度自适应",
                fieldName: "autosize",
                fieldType: "switch",
                required: false,
                selectValues: "[true,false]",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
            {
                label: "占位信息",
                fieldName: "placeholder",
                fieldType: "input",
                required: false,
                selectValues: "",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
            {
                label: "输入框尺寸",
                fieldName: "size",
                fieldType: "select",
                required: false,
                selectValues: [
                    {name: "大", value: "large"},
                    {name: "中", value: "default"},
                    {name: "小", value: "small"},
                ],
                defaultValues: "",
                category: 2,
                configParams: [],
            },
        ],
        selfFields: [],
        actions: [],
        preps: [],
    },
    {
        itemName: "下拉联动",
        itemType: "relation-select",
        itemIcon: "input",
        category: 3,
        fields: [
            {
                label: "值类型",
                fieldName: "valueType",
                fieldType: "select",
                required: false,
                selectValues: commonSelectOptions,
                defaultValues: "",
                category: 1,
                configParams: [],
            },
        ],
        advancedFields: [],
        selfFields: [],
        actions: [],
        preps: [],
    },

    {
        itemName: "区域",
        itemType: "area",
        itemIcon: "text",
        category: 3,
        fields: [
            {
                label: "可搜索",
                fieldName: "filterable",
                fieldType: "switch",
                required: false,
                selectValues: "[true,false]",
                defaultValues: "",
                category: 1,
                configParams: [],
            },
        ],
        advancedFields: [],
        selfFields: [],
        actions: [],
        preps: [],
    },
    {
        itemName: "视频播放器",
        itemType: "vedio",
        itemIcon: "vedio",
        category: 3,
        fields: [],
        advancedFields: [],
        selfFields: [],
        actions: [],
        preps: [],
    },
    {
        itemName: "JSON",
        itemType: "json",
        itemIcon: "text",
        category: 3,
        fields: [
            {
                label: "开发者模式",
                fieldName: "devType",
                fieldType: "switch",
                required: false,
                selectValues: "[true,false]",
                defaultValues: "",
                category: 1,
                configParams: [],
            },
        ],
        advancedFields: [],
        selfFields: [],
        actions: [],
        preps: [],
    },
    {
        itemName: "音频播放器",
        itemType: "audio",
        itemIcon: "audio",
        category: 3,
        fields: [],
        advancedFields: [],
        selfFields: [],
        actions: [],
        preps: [],
    },
    {
        itemName: "MarkDown",
        itemType: "markdown",
        itemIcon: "text",
        category: 3,
        fields: [],
        advancedFields: [],
        selfFields: [],
        actions: [],
        preps: [],
    },
    {
        itemName: "签名",
        itemType: "signature",
        itemIcon: "text",
        category: 3,
        fields: [
            {
                label: "宽度",
                fieldName: "width",
                required: false,
                fieldType: "number",
                defaultValues: "350",
                category: 1,
            }, {
                label: "高度",
                fieldName: "height",
                required: false,
                fieldType: "number",
                defaultValues: "100",
                category: 1,
            }, {
                label: "画笔最小宽度(px)",
                fieldName: "minWidth",
                required: false,
                fieldType: "number",
                defaultValues: "2",
                category: 1,
            }, {
                label: "画笔最大宽度(px)",
                fieldName: "minWidth",
                required: false,
                fieldType: "number",
                defaultValues: "6",
                category: 1,
            }

        ],
        advancedFields: [{
            label: "是否开启笔锋效果",
            fieldName: "openSmooth",
            required: false,
            fieldType: "switch",
            defaultValues: true,
            category: 2,
        }
            , {
                label: "画笔达到最小宽度所需最小速度(px/ms)",
                fieldName: "minWidth",
                required: false,
                helpMsg: "画笔达到最小宽度所需最小速度(px/ms),取值范围1.0-10.0，值越小，画笔越容易变细，笔锋效果会比较明显，可以自行调整查看效果，选出自己满意的值",
                fieldType: "number",
                defaultValues: "1.5",
                category: 2,
            }],
        selfFields: [],
        actions: [],
        preps: [],
    },
    {
        itemName: "JSON数组",
        itemType: "json-array",
        itemIcon: "text",
        category: 3,
        fields: [
            {
                label: "开发者模式",
                fieldName: "devType",
                fieldType: "switch",
                required: false,
                selectValues: "[true,false]",
                defaultValues: "",
                category: 1,
                configParams: [],
            },
        ],
        advancedFields: [],
        selfFields: [],
        actions: [],
        preps: [],
    },

    {
        itemName: "系统组件",
        itemType: "usercomp",
        itemIcon: "setting",
        category: 3,
        fields: [
            {
                label: "组件名称",
                fieldName: "compName",
                fieldType: "input",
                required: true,
                selectValues: "",
                defaultValues: "",
                category: 1,
                remark: "只能是components/common目录下的组件，n不能带目录2",
                configParams: [],
            },
            {
                label: "组件目录",
                fieldName: "compDirName",
                fieldType: "input",
                required: false,
                selectValues: "",
                defaultValues: "",
                category: 1,
                remark: "",
                configParams: [],
            },
        ],
        advancedFields: [],
        selfFields: [],
        actions: [],
        preps: [],
    },
    {
        itemName: "二维码",
        itemType: "qrcode",
        itemIcon: "qrcode",
        category: 3,
        fields: [
            {
                label: "二维码颜色",
                fieldName: "color",
                fieldType: "input",
                required: false,
                selectValues: "",
                defaultValues: "#000",
                category: 1,
                configParams: [],
            },
            {
                label: "尺寸",
                fieldName: "size",
                fieldType: "input",
                required: false,
                selectValues: "",
                defaultValues: "160",
                category: 1,
                configParams: [],
            },
            {
                label: "背景色",
                fieldName: "bgColor",
                fieldType: "input",
                required: false,
                selectValues: "",
                defaultValues: "#fff",
                category: 1,
                configParams: [],
            },
            {
                label: "纠错等级",
                fieldName: "level",
                fieldType: "select",
                required: false,
                selectValues: [
                    {name: "低", value: "L"},
                    {name: "中", value: "M"},
                    {name: "1/4", value: "Q"},
                    {name: "高", value: "H"},
                ],
                defaultValues: "M",
                category: 1,
                configParams: [],
            },
            {
                label: "二维码状态",
                fieldName: "status",
                fieldType: "select",
                required: false,
                selectValues: [
                    {name: "激活", value: "active"},
                    {name: "过期", value: "expired"},
                    {name: "加载中", value: "loading"},
                    {name: "已浏览", value: "scanned"},
                ],
                defaultValues: "active",
                category: 1,
                configParams: [],
            },
            {
                label: "渲染类型",
                fieldName: "type",
                fieldType: "select",
                required: false,
                selectValues: [
                    {name: "Canvas", value: "canvas"},
                    {name: "Svg", value: "svg"},
                ],
                defaultValues: "svg",
                category: 1,
                configParams: [],
            },
        ],
        advancedFields: [
            {
                label: "图片地址",
                fieldName: "icon",
                fieldType: "input",
                required: false,
                selectValues: "",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
            {
                label: "图片大小",
                fieldName: "iconSize",
                fieldType: "input",
                required: false,
                selectValues: "",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
            {
                label: "图片设置",
                fieldName: "iconsettings",
                fieldType: "json",
                required: false,
                selectValues: "",
                defaultValues: "",
                category: 2,
                configParams: [],
            },
        ],
        selfFields: [],
        actions: [],
        preps: [],
    },
    {
        itemName: "条形码",
        itemType: "barcode",
        itemIcon: "date-range-field",
        category: 3,
        fields: [
            {
                label: "缩放",
                fieldName: "scale",
                fieldType: "input",
                required: false,
                selectValues: "",
                defaultValues: "3",
                category: 1,
                configParams: [],
            },
            {
                label: "是否显示文本",
                fieldName: "includeText",
                fieldType: "switch",
                required: false,
                selectValues: "",
                defaultValues: "true",
                category: 1,
                configParams: [],
            },
            {
                label: "高度",
                fieldName: "height",
                fieldType: "input",
                required: false,
                selectValues: "",
                defaultValues: "10",
                category: 1,
                configParams: [],
            },
            {
                label: "对齐方式",
                fieldName: "textAlign",
                fieldType: "select",
                required: false,
                selectValues: [
                    {name: "左", value: "left"},
                    {name: "中", value: "center"},
                    {name: "右", value: "right"},
                ],
                defaultValues: "center",
                category: 1,
                configParams: [],
            },
            {
                label: "条形码风格",
                fieldName: "bcid",
                fieldType: "input",
                required: false,
                selectValues: "",
                defaultValues: "code128",
                category: 1,
                configParams: [],
            },
        ],
        advancedFields: [],
        selfFields: [],
        actions: [],
        preps: [],
    },
    {
        itemName: "地址",
        itemType: "area",
        itemIcon: "position",
        category: 3,
        fields: [],
        advancedFields: [],
        selfFields: [],
        actions: [],
        preps: [],
    },
];
