import { PageComp } from '@/components/types/PageLayoutComp.ts';

export const pageCompList: PageComp[] = [
  {
    id: 'a',
    label: '系统组件',
    name: 'system',
    icon: 'system',
    items: [
      {
        id: '1',
        label: '表格',
        name: 'ptable',
        icon: 'table',
        preps: {},
      },
      {
        id: '2',
        label: '分页条',
        name: 'ppagebar',
        icon: 'pagebar',
        preps: {
          layout: 'prev,pager,next',
          total: 1000,
        },
      },
      {
        id: '3',
        label: '图片',
        name: 'pimage',
        icon: 'image',
        preps: {},
      },
      {
        id: '4',
        label: '走马灯',
        name: 'pcarousel',
        icon: 'carousel',
        preps: {},
      },
      {
        id: '5',
        label: '日历',
        name: 'pcalendar',
        icon: 'calendar',
        preps: {},
      },
      {
        id: '6',
        label: '分割面板',
        name: 'psplitter',
        icon: 'splitter',
        preps: {},
      },
      {
        id: '7',
        label: '统计',
        name: 'pstatistic',
        icon: 'statistic',
        preps: {},
      },
      {
        id: '8',
        label: '页头',
        name: 'ppageheader',
        icon: 'pageHeader',
        preps: {},
      },
      {
        id: '9',
        label: '菜单',
        name: 'pmenubar',
        icon: 'menu',
        preps: {},
      },
      {
        id: '10',
        label: '步骤条',
        name: 'psteps',
        icon: 'steps',
        preps: {},
      },
      {
        id: '11',
        label: '时间线',
        name: 'ptimeline',
        icon: 'timeline',
        preps: {},
      },
      {
        id: '12',
        label: '表单',
        name: 'pform',
        icon: 'form',
        preps: {},
      },
    ],
    container: {},
  },
  {
    id: 'b',
    label: '自定义组件',
    name: 'custom',
    icon: 'custom',
    items: [],
    container: {},
  },
];
