import { PageComp } from "@/components/types/PageLayoutComp.ts";

export const pageCompList: PageComp[] = [
  {
    id: "a",
    label: "系统组件",
    name: "system",
    icon: "system",
    items: [
      {
        id: "1",
        label: "表格",
        name: "ptable",
        icon: "table",
        preps: {},
      },
      {
        id: "2",
        label: "分页条",
        name: "ppagebar",
        icon: "pagebar",
        preps: {
          layout: "prev,pager,next",
          total: 1000,
        },
      },
      {
        id: "3",
        label: "图片",
        name: "pimage",
        icon: "image",
        preps: {},
      },
      {
        id: "4",
        label: "走马灯",
        name: "pcarousel",
        icon: "carousel",
        preps: {},
      },
      {
        id: "5",
        label: "日历",
        name: "pcalendar",
        icon: "calendar",
        preps: {},
      },
      {
        id: "6",
        label: "分割面板",
        name: "psplitter",
        icon: "splitter",
        preps: {},
      },
      {
        id: "7",
        label: "统计",
        name: "pstatistic",
        icon: "statistic",
        preps: {},
      },
      {
        id: "8",
        label: "页头",
        name: "ppageheader",
        icon: "pageHeader",
        preps: {},
      },
      {
        id: "9",
        label: "菜单",
        name: "pmenubar",
        icon: "menu",
        preps: {},
      },
      {
        id: "10",
        label: "步骤条",
        name: "psteps",
        icon: "steps",
        preps: {},
      },
      {
        id: "11",
        label: "时间线",
        name: "ptimeline",
        icon: "timeline",
        preps: {},
      },
      {
        id: "12",
        label: "表单",
        name: "pform",
        icon: "form",
        preps: {},
      },
      {
        id: "13",
        label: "轮播图",
        name: "pbanner",
        icon: "banner",
        preps: {},
      },
      {
        id: "14",
        label: "卡片",
        name: "pcard",
        icon: "card",
        preps: {},
      },
      {
        id: "15",
        label: "内容展示",
        name: "pcontent",
        icon: "content",
        preps: {},
      },
      {
        id: "16",
        label: "版权信息",
        name: "pcopyright",
        icon: "copyright",
        preps: {},
      },
      {
        id: "17",
        label: "横向菜单",
        name: "phmenu",
        icon: "hmenu",
        preps: {},
      },
      {
        id: "18",
        label: "链接",
        name: "plink",
        icon: "link",
        preps: {},
      },
      {
        id: "19",
        label: "Logo",
        name: "plogo",
        icon: "logo",
        preps: {},
      },
      {
        id: "20",
        label: "导航栏",
        name: "pnavbar",
        icon: "navbar",
        preps: {},
      },
      {
        id: "21",
        label: "图表",
        name: "chart",
        icon: "chart",
        preps: {
          type: "line",
          option: {
            title: { text: "折线图示例" },
            tooltip: { trigger: "axis" },
            xAxis: {
              type: "category",
              data: ["周一", "周二", "周三", "周四", "周五", "周六", "周日"],
            },
            yAxis: { type: "value" },
            series: [
              {
                data: [120, 200, 150, 80, 70, 110, 130],
                type: "line",
                smooth: true,
              },
            ],
          },
        },
      },
    ],
    container: {},
  },
  {
    id: "b",
    label: "自定义组件",
    name: "custom",
    icon: "custom",
    items: [],
    container: {},
  },
];
